# -*- coding: utf-8 -*-
"""Anosha-DataStructure.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Aqo_-pr3Zi2L5AEqIkg7anQl8XwB7NcE

**DSMP Fellowship Assignment 0.2**

Step 1: Create a list called attendance_list with the names:

["John", "Emma", "John", "Ava", "Sophia", "Emma"]

Step 2: Print the list to see the attendance.

Step 3: Count how many names (including duplicates) are in the list and print the total number.
"""

attendance_list = ["John", "Emma", "John", "Ava", "Sophia", "Emma"]
print(attendance_list)
print("Total Student : ", len(attendance_list))

"""**Question 2: Unique Attendance using a Set**

Step 1: Convert the attendance_list from Question 1 into a set.

Step 2: Print the set to see the unique student names.

Step 3: Count and print the total number of unique students.
"""

attendance_set = {"John", "Emma", "John", "Ava", "Sophia", "Emma"}
print(attendance_set)
print("Total Unique Student : ", len(attendance_set))

"""**Question 3: Storing Attendance Permanently with a Tuple**

Step 1: Create a tuple called attendance_tuple with these names:

("John", "Emma", "Ava", "Sophia")

Step 2: Print the tuple to display the names.
"""

attendance_tuple = ("John", "Emma", "Ava", "Sophia")
print(attendance_tuple)

"""**Question 4: Count Attendance using a Dictionary**

Step 1: Using the attendance_list from Question 1, create a dictionary where each student's name is a key, and the number of times they attended is the value.

Step 2: Print the dictionary to see each student's attendance count.
"""

attendance_dictionary = {
    "John": 10,
    "Emma": 9,
    "Ava": 8,
    "Sophia": 10}
print(attendance_dictionary)
print(attendance_dictionary.values())